# Generated by Django 5.2.12 on 2026-08-11 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking_request',
            new_name='bookings_bo_lsa_id_05ea35_idx',
            old_name='bookings_boo_lsa_id_4b9d5f_idx',
        ),
        migrations.RenameIndex(
            model_name='booking_request',
            new_name='bookings_bo_status_e4429d_idx',
            old_name='bookings_boo_status_6e4db6_idx',
        ),
        migrations.RenameIndex(
            model_name='lsa_profile',
            new_name='bookings_ls_is_acti_6ab1fc_idx',
            old_name='bookings_lsa_is_acti_9d3a1e_idx',
        ),
    ]
