# Generated by Django 5.2.12 on 2026-08-12 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_bookings_boo_lsa_id_4b9d5f_idx_bookings_bo_lsa_id_05ea35_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='MOCK', max_length=50)),
                ('external_reference', models.CharField(max_length=120, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking_request')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='bookings_pa_status_e13a34_idx'), models.Index(fields=['external_reference'], name='bookings_pa_externa_c07f53_idx')],
            },
        ),
    ]
